import { InterviewQuestion } from '@/types/database';

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // =========================================================================
  // ECE & SEMICONDUCTOR QUESTIONS
  // =========================================================================
  {
    id: 'ece-q-1',
    title: 'Setup and Hold Time Slack Calculation with Clock Skew',
    domain: 'ece',
    company_ids: ['comp-nvidia', 'comp-amd', 'comp-intel', 'comp-broadcom'],
    company_names: ['NVIDIA', 'AMD', 'Intel', 'Broadcom'],
    category: 'STA & Timing Analysis',
    subtopic: 'Slack & Clock Skew',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Given Flip-Flop T_cq = 2ns, T_setup = 1.5ns, T_hold = 1ns, T_comb_max = 6ns, T_comb_min = 2ns, Clock Period T_clk = 10ns, and Clock Skew = 0.5ns (positive). Calculate Setup Slack and Hold Slack. Is there any violation?',
    answer_outline: 'Setup Check: Data arrival time = T_cq + T_comb_max = 2 + 6 = 8ns. Data required time = T_clk + T_skew - T_setup = 10 + 0.5 - 1.5 = 9.0ns. Setup Slack = Required - Arrival = 9.0 - 8.0 = +1.0ns (NO setup violation).\nHold Check: Data arrival time = T_cq + T_comb_min = 2 + 2 = 4ns. Data required time = T_hold + T_skew = 1 + 0.5 = 1.5ns. Hold Slack = Arrival - Required = 4.0 - 1.5 = +2.5ns (NO hold violation). Both margins are positive.',
    key_concepts: ['Setup Slack', 'Hold Slack', 'Positive Skew', 'Launch Edge', 'Capture Edge'],
    practice_url: 'https://www.geeksforgeeks.org/setup-and-hold-time-in-digital-logic/'
  },
  {
    id: 'ece-q-2',
    title: 'Why Can Hold Violations NOT be Fixed by Reducing Clock Frequency?',
    domain: 'ece',
    company_ids: ['comp-intel', 'comp-amd', 'comp-qualcomm', 'comp-ti'],
    company_names: ['Intel', 'AMD', 'Qualcomm', 'Texas Instruments'],
    category: 'STA & Timing Analysis',
    subtopic: 'Physical Design',
    difficulty: 'Easy',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'An engineer notices a hold time violation on silicon post-fabrication. Can lowering the operating clock frequency from 1GHz to 500MHz solve the hold failure? Explain the fundamental physical reason.',
    answer_outline: 'NO. Clock period T_clk does not appear in the hold slack equation: T_cq + T_comb >= T_hold + T_skew. Hold time checks whether data launched at time t=0 reaches the destination flip-flop before the same capture clock edge at t=0 has finished holding previous data. Because both launch and capture are triggered by the identical clock pulse, changing clock period has zero impact on hold slack. Hold violations can only be fixed by adding delay buffers in the data path.',
    key_concepts: ['Hold Slack Independence', 'Same Clock Edge', 'Delay Buffers', 'Post-Silicon Failure']
  },
  {
    id: 'ece-q-3',
    title: 'Clock Domain Crossing (CDC) & 2-Flip-Flop Synchronizer',
    domain: 'ece',
    company_ids: ['comp-nvidia', 'comp-broadcom', 'comp-samsung-semicon'],
    company_names: ['NVIDIA', 'Broadcom', 'Samsung Semiconductor'],
    category: 'STA & Timing Analysis',
    subtopic: 'Metastability & CDC',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'What is metastability in digital circuits? Why is a 2-flip-flop synchronizer effective for single-bit asynchronous signal crossing, and what are its limitations for multi-bit buses?',
    answer_outline: 'When setup or hold times are violated, flip-flop bistable feedback enters an intermediate voltage state neither 0 nor 1, taking indeterminate time to resolve. A 2-flop synchronizer gives the first flop one full clock cycle to settle to a stable logic state before the second flop samples it, dramatically increasing Mean Time Between Failures (MTBF). For multi-bit buses, independent bit delays cause skew, meaning bits may arrive in different clock cycles (corrupting bus state). Therefore, multi-bit CDC requires Gray-coded pointers, Async FIFOs, or Request-Acknowledge handshakes.',
    key_concepts: ['Metastability', 'MTBF', '2-FF Synchronizer', 'Multi-bit Skew', 'Gray Code']
  },
  {
    id: 'ece-q-4',
    title: 'Asynchronous FIFO Depth Calculation Formula',
    domain: 'ece',
    company_ids: ['comp-broadcom', 'comp-nvidia', 'comp-qualcomm'],
    company_names: ['Broadcom', 'NVIDIA', 'Qualcomm'],
    category: 'STA & Timing Analysis',
    subtopic: 'FIFO Architecture',
    difficulty: 'Hard',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Write clock writes 80 data bytes every 100 clock cycles at 100MHz. Read clock reads 8 data bytes every 10 clock cycles at 80MHz. What is the minimum asynchronous FIFO depth required to prevent overflow during worst-case burst?',
    answer_outline: 'Write frequency f_w = 100MHz (period 10ns). Write burst = 80 bytes in 800ns (worst-case: 80 bytes sent back-to-back at end of first period and start of next, max burst = 80 bytes in 80 cycles = 800ns). Read frequency f_r = 80MHz (period 12.5ns). Read throughput = 8 bytes in 10 cycles (125ns). In 800ns, read cycles = 800 / 125 = 6.4 bursts -> 6.4 * 8 = 51.2 bytes read (conservatively 51 bytes). FIFO depth = 80 - 51 = 29 bytes. Rounding up with safety margins gives depth 30 or 32 (power of 2).',
    key_concepts: ['Worst-Case Burst', 'Async FIFO Depth', 'Throughput Mismatch']
  },
  {
    id: 'ece-q-5',
    title: 'Blocking (=) vs Non-Blocking (<=) Assignment in Verilog',
    domain: 'ece',
    company_ids: ['comp-intel', 'comp-amd', 'comp-nvidia', 'comp-ti'],
    company_names: ['Intel', 'AMD', 'NVIDIA', 'Texas Instruments'],
    category: 'Verilog & SystemVerilog',
    subtopic: 'Synthesis Semantics',
    difficulty: 'Easy',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Explain the difference between blocking and non-blocking assignments in synthesizable Verilog. What happens if you use blocking assignments in sequential always @(posedge clk) blocks?',
    answer_outline: 'Blocking (=) executes sequentially in simulation: statement evaluates and immediately updates target before moving to the next line. Non-blocking (<=) schedules assignment into the Non-Blocking Assignment (NBA) event queue; all RHS values are sampled at start of time step and updated at the end concurrently. If blocking is used in posedge clk blocks, synthesis generates shift registers with race conditions where register Q outputs bypass downstream registers instantly instead of delaying by 1 cycle.',
    code_snippet: '// WRONG (Race condition in sequential logic):\nalways @(posedge clk) begin\n  b = a;\n  c = b; // c gets new value of a immediately!\nend\n\n// CORRECT (Proper 2-stage shift register):\nalways @(posedge clk) begin\n  b <= a;\n  c <= b; // c gets previous value of b\nend',
    key_concepts: ['NBA Queue', 'Event Queue', 'Race Conditions', 'Shift Registers']
  },
  {
    id: 'ece-q-6',
    title: 'Detect Overlapping Sequence 1011 using Moore FSM',
    domain: 'ece',
    company_ids: ['comp-intel', 'comp-qualcomm', 'comp-samsung-semicon'],
    company_names: ['Intel', 'Qualcomm', 'Samsung Semiconductor'],
    category: 'Digital Electronics',
    subtopic: 'FSM Design',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Design a Moore State Machine that detects sequence "1011" on an input bitstream with overlapping detection. Draw state transition diagram and determine total number of states.',
    answer_outline: 'For Moore machine detecting length-N sequence, N+1 states are required. States: S0 (Init), S1 ("1"), S2 ("10"), S3 ("101"), S4 ("1011" - Output=1). Transitions: From S4 on input 1 -> S1 (since suffix "1" matches start of next sequence); on input 0 -> S2 (since suffix "10" matches prefix of next sequence!). This enables overlapping detection (e.g. 1011011 produces two outputs).',
    key_concepts: ['Moore FSM', 'Overlapping Detection', 'State Transition Table', 'Sequence Detector']
  },
  {
    id: 'ece-q-7',
    title: 'Volatile Keyword & Register Mapping in Embedded C',
    domain: 'ece',
    company_ids: ['comp-qualcomm', 'comp-bosch', 'comp-nxp', 'comp-continental'],
    company_names: ['Qualcomm', 'Bosch Global Software', 'NXP', 'Continental Automotive'],
    category: 'Embedded C & RTOS',
    subtopic: 'Low-Level C',
    difficulty: 'Easy',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'What does the volatile keyword do in C? Why is it essential for hardware memory-mapped peripheral registers, and what can go wrong if it is omitted in an interrupt-driven system?',
    answer_outline: 'volatile informs compiler that variable value can change unexpectedly outside current code flow (e.g. by hardware peripherals or ISR). It disables aggressive compiler optimizations like caching variable in CPU register. If omitted in a polling loop like while(!flag), compiler may optimize it to an infinite loop if(flag == 0) while(1); because it assumes loop body never modifies flag.',
    code_snippet: '// Memory-mapped peripheral register pointer:\n#define UART_STATUS_REG (*((volatile uint32_t *)0x40001000))\n\n// Polling loop (guaranteed to re-read bus memory every cycle):\nwhile ((UART_STATUS_REG & (1 << 5)) == 0) {\n  // wait for TX ready\n}',
    key_concepts: ['Compiler Optimization', 'Memory-Mapped I/O', 'ISR Shared Variables', 'Cache Bypass']
  },
  {
    id: 'ece-q-8',
    title: 'Priority Inversion Problem & Priority Inheritance in RTOS',
    domain: 'ece',
    company_ids: ['comp-qualcomm', 'comp-bosch', 'comp-honeywell'],
    company_names: ['Qualcomm', 'Bosch Global Software', 'Honeywell Aerospace'],
    category: 'Embedded C & RTOS',
    subtopic: 'Real-Time Concurrency',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Explain Priority Inversion using three tasks (High, Medium, Low). How did this cause the famous Mars Pathfinder spacecraft reset, and how does Priority Inheritance Protocol resolve it?',
    answer_outline: 'Scenario: Low task acquires shared Mutex M. High task preempts Low and requests Mutex M -> High blocks waiting for Low to release M. Medium task (which does not need M) preempts Low task because Medium priority > Low priority. High task is now indirectly blocked by Medium task indefinitely! Solution: Priority Inheritance temporarily elevates Low task priority to High task level while Low holds Mutex M, preventing Medium task from preempting Low until Mutex M is released.',
    key_concepts: ['Priority Inversion', 'Priority Inheritance', 'Deadlock Prevention', 'Mars Pathfinder']
  },
  {
    id: 'ece-q-9',
    title: 'CAN Protocol Arbitration: Why Dominant Bit Wins',
    domain: 'ece',
    company_ids: ['comp-bosch', 'comp-continental', 'comp-nxp', 'comp-infineon'],
    company_names: ['Bosch Global Software', 'Continental Automotive', 'NXP', 'Infineon Technologies'],
    category: 'Microcontrollers & Protocols',
    subtopic: 'CAN Bus & Automotive',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Explain CSMA/CD + Non-Destructive Bitwise Arbitration in CAN protocol. Why does a lower numerical Message ID (e.g., 0x100) have higher priority than 0x200?',
    answer_outline: 'CAN physical bus uses wired-AND logic: Logic 0 is Dominant (CAN_H pulls high, CAN_L pulls low, differential voltage ~2V). Logic 1 is Recessive (differential voltage ~0V). If Node A transmits 0 and Node B transmits 1 simultaneously, the bus shows 0. Both nodes monitor the bus while transmitting: Node B sees that bus value (0) does not match its transmitted bit (1), detects collision, stops transmitting immediately, and waits. Node A continues transmission without losing a single bit (non-destructive). Lower message IDs start with more leading zeroes, hence win bus priority.',
    key_concepts: ['Dominant vs Recessive', 'Differential Signaling', 'Non-Destructive Arbitration', 'Wired-AND']
  },
  {
    id: 'ece-q-10',
    title: 'Derive Small-Signal Voltage Gain of Common-Source Amplifier with Source Degeneration',
    domain: 'ece',
    company_ids: ['comp-ti', 'comp-adi', 'comp-stmicro', 'comp-infineon'],
    company_names: ['Texas Instruments', 'Analog Devices (ADI)', 'STMicroelectronics', 'Infineon Technologies'],
    category: 'Analog Electronics & Op-Amps',
    subtopic: 'MOSFET Small Signal',
    difficulty: 'Hard',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Draw small-signal equivalent circuit of NMOS Common-Source amplifier with load resistor Rd and source degeneration resistor Rs (neglect channel-length modulation lambda=0). Derive exact voltage gain Av = Vout / Vin.',
    answer_outline: 'Small signal relations: Vout = - gm * Vgs * Rd. KVL at input loop: Vin = Vgs + Vs = Vgs + (gm * Vgs) * Rs = Vgs * (1 + gm * Rs). Substituting Vgs = Vin / (1 + gm * Rs) into Vout gives: Vout = - (gm * Vin * Rd) / (1 + gm * Rs). Voltage gain Av = - (gm * Rd) / (1 + gm * Rs). If gm*Rs >> 1, gain simplifies to -Rd / Rs (linearized gain dependent strictly on resistor ratios, independent of transistor transconductance).',
    key_concepts: ['Source Degeneration', 'Transconductance gm', 'Gain Linearization', 'Negative Feedback']
  },
  {
    id: 'ece-q-11',
    title: 'UVM Testbench Architecture & Phase Flow',
    domain: 'ece',
    company_ids: ['comp-synopsys', 'comp-cadence', 'comp-qualcomm', 'comp-intel'],
    company_names: ['Synopsys', 'Cadence Design Systems', 'Qualcomm', 'Intel'],
    category: 'UVM & Verification',
    subtopic: 'UVM Phases',
    difficulty: 'Hard',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'What are the main UVM build and run phases? Explain why build_phase executes top-down while connect_phase executes bottom-up.',
    answer_outline: 'UVM Phases: build_phase, connect_phase, end_of_elaboration, start_of_simulation, run_phase (time-consuming task), extract_phase, check_phase, report_phase. build_phase runs TOP-DOWN so parent components (like test or env) can configure and instantiate child components (like agents and drivers) using the factory. connect_phase runs BOTTOM-UP so leaf components instantiate their TLM ports and exports before parent entities wire them together.',
    key_concepts: ['UVM Phases', 'Top-Down Build', 'Bottom-Up Connect', 'TLM Ports', 'Factory Registration']
  },
  {
    id: 'ece-q-12',
    title: 'Pipeline Hazards in RISC-V: Data, Control, and Structural',
    domain: 'ece',
    company_ids: ['comp-nvidia', 'comp-amd', 'comp-arm', 'comp-intel'],
    company_names: ['NVIDIA', 'AMD', 'Arm', 'Intel'],
    category: 'Computer Architecture & RISC-V',
    subtopic: 'Pipeline Hazards',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'In a 5-stage RISC-V pipeline (IF, ID, EX, MEM, WB), explain RAW Data Hazard and how Operand Forwarding eliminates stalls for ALU-to-ALU instructions. When is a stall bubble unavoidable?',
    answer_outline: 'Read-After-Write (RAW) occurs when an instruction in ID stage needs a register written by an instruction currently in EX or MEM stage. Forwarding multiplexes result directly from EX/MEM or MEM/WB pipeline registers into the ALU inputs, eliminating stalls for ALU-ALU dependencies. However, in Load-Use hazards (lw x1, 0(x2) followed by add x3, x1, x4), the load data is only available after MEM stage, whereas add needs it at EX stage. This requires 1 unavoidable stall cycle even with forwarding.',
    key_concepts: ['RAW Hazard', 'Operand Forwarding', 'Load-Use Stall', '5-Stage Pipeline']
  },
  {
    id: 'ece-q-13',
    title: 'I2C Protocol: Clock Stretching and ACK/NACK Generation',
    domain: 'ece',
    company_ids: ['comp-ti', 'comp-nxp', 'comp-stmicro', 'comp-bosch'],
    company_names: ['Texas Instruments', 'NXP', 'STMicroelectronics', 'Bosch Global Software'],
    category: 'Microcontrollers & Protocols',
    subtopic: 'I2C Bus',
    difficulty: 'Easy',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Why does the I2C bus require open-drain pins with pull-up resistors? How does a slow slave device hold the master using Clock Stretching?',
    answer_outline: 'Open-drain ensures that when multiple devices drive the bus, no short circuit (VCC to GND contention) occurs; any device pulling LOW creates a wired-AND LOW. Clock Stretching allows a slow slave to hold SCL LOW after an address/data byte. The master senses that SCL has not risen to HIGH (due to open-drain pull-up) and pauses until the slave finishes processing and releases SCL.',
    key_concepts: ['Open Drain', 'Clock Stretching', 'Pull-up Resistors', 'Wired-AND']
  },
  {
    id: 'ece-q-14',
    title: 'Scan Chains and Stuck-At Fault Models in DFT',
    domain: 'ece',
    company_ids: ['comp-synopsys', 'comp-cadence', 'comp-intel', 'comp-broadcom'],
    company_names: ['Synopsys', 'Cadence Design Systems', 'Intel', 'Broadcom'],
    category: 'VLSI Physical Design & DFT',
    subtopic: 'Design For Testability',
    difficulty: 'Hard',
    frequency: 'Medium',
    round_type: 'Technical',
    question_text: 'What is a Scan Flip-Flop? How does converting regular flip-flops into scan chains improve test coverage for Stuck-At-0 and Stuck-At-1 manufacturing faults?',
    answer_outline: 'A Scan Flip-Flop incorporates a 2:1 multiplexer before data input controlled by Scan Enable (SE). In normal mode (SE=0), it operates on functional data. In scan mode (SE=1), flip-flops are connected in series forming a massive shift register. This solves the controllability and observability problem in sequential logic: test patterns can be shifted into internal registers directly, circuit runs 1 clock cycle, and results are shifted out to identify stuck-at faults with ATPG algorithms.',
    key_concepts: ['Scan Flip-Flop', 'Scan Chain', 'Controllability & Observability', 'ATPG', 'Stuck-At Fault']
  },
  {
    id: 'ece-q-15',
    title: 'Efficient Circular Buffer / Ring Buffer Implementation in C',
    domain: 'ece',
    company_ids: ['comp-qualcomm', 'comp-bosch', 'comp-continental'],
    company_names: ['Qualcomm', 'Bosch Global Software', 'Continental Automotive'],
    category: 'Embedded C & RTOS',
    subtopic: 'Data Structures in C',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Write a thread-safe / ISR-safe circular buffer in C. How can power-of-two buffer sizes optimize modulo operations in microcontrollers without hardware division?',
    answer_outline: 'When buffer size is a power of 2 (e.g. 64 or 256), the modulo operation index % SIZE can be replaced by fast bitwise AND: index & (SIZE - 1). This executes in 1 clock cycle compared to multi-cycle integer division. For single-producer single-consumer lock-free safety, read and write pointers should be declared volatile and modified only by their respective contexts.',
    code_snippet: '#define BUFFER_SIZE 64 // Must be power of 2!\ntypedef struct {\n    uint8_t data[BUFFER_SIZE];\n    volatile uint16_t head;\n    volatile uint16_t tail;\n} RingBuffer;\n\nstatic inline bool rb_put(RingBuffer* rb, uint8_t byte) {\n    uint16_t next = (rb->head + 1) & (BUFFER_SIZE - 1);\n    if (next == rb->tail) return false; // Buffer full\n    rb->data[rb->head] = byte;\n    rb->head = next;\n    return true;\n}',
    key_concepts: ['Power-of-Two Optimization', 'Bitwise Masking', 'Lock-Free FIFO', 'Interrupt Safety']
  },

  // =========================================================================
  // SOFTWARE & IT INTERVIEW QUESTIONS
  // =========================================================================
  {
    id: 'it-q-1',
    title: 'Longest Palindromic Substring (Expand Around Center vs Manacher)',
    domain: 'it',
    company_ids: ['comp-google', 'comp-amazon', 'comp-microsoft'],
    company_names: ['Google', 'Amazon', 'Microsoft'],
    category: 'DSA & Problem Solving',
    subtopic: 'Dynamic Programming & Strings',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Given a string s, return the longest palindromic substring in s. Provide an optimal solution with O(N^2) time and O(1) auxiliary space, and explain how to optimize to O(N) using Manacher algorithm.',
    answer_outline: 'Expand Around Center: Palindromes can have odd length (centered at character i) or even length (centered between i and i+1). For each of 2N-1 centers, expand outward while s[left] == s[right]. Time complexity O(N^2), Space O(1). Manacher algorithm pre-processes string with delimiter "#" to unify odd/even lengths, tracks current palindrome center and rightmost boundary, achieving O(N) linear time.',
    code_snippet: 'string longestPalindrome(string s) {\n    int n = s.size(), start = 0, maxLen = 0;\n    auto expand = [&](int l, int r) {\n        while (l >= 0 && r < n && s[l] == s[r]) l--, r++;\n        if (r - l - 1 > maxLen) { start = l + 1; maxLen = r - l - 1; }\n    };\n    for (int i = 0; i < n; i++) {\n        expand(i, i);     // Odd\n        expand(i, i + 1); // Even\n    }\n    return s.substr(start, maxLen);\n}',
    key_concepts: ['Expand Around Center', 'Manachers Algorithm', 'Two Pointers', 'String Palindromes'],
    practice_url: 'https://leetcode.com/problems/longest-palindromic-substring/'
  },
  {
    id: 'it-q-2',
    title: 'Trapping Rain Water (Two Pointers vs Monotonic Stack)',
    domain: 'it',
    company_ids: ['comp-google', 'comp-amazon', 'comp-flipkart', 'comp-goldman'],
    company_names: ['Google', 'Amazon', 'Flipkart', 'Goldman Sachs'],
    category: 'DSA & Problem Solving',
    subtopic: 'Arrays & Two Pointers',
    difficulty: 'Hard',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    answer_outline: 'Two Pointer Approach: Water trapped above bar i is determined by min(max_left, max_right) - height[i]. Use left and right pointers moving inwards. If height[left] < height[right], trapped water depends strictly on left_max because right wall is guaranteed to be taller; update left_max and accumulate water, then advance left. Time O(N), Space O(1).',
    code_snippet: 'int trap(vector<int>& height) {\n    int l = 0, r = height.size() - 1;\n    int lmax = 0, rmax = 0, total = 0;\n    while (l < r) {\n        if (height[l] < height[r]) {\n            height[l] >= lmax ? lmax = height[l] : total += (lmax - height[l]);\n            l++;\n        } else {\n            height[r] >= rmax ? rmax = height[r] : total += (rmax - height[r]);\n            r--;\n        }\n    }\n    return total;\n}',
    key_concepts: ['Two Pointers', 'Bounding Wall', 'O(1) Auxiliary Space'],
    practice_url: 'https://leetcode.com/problems/trapping-rain-water/'
  },
  {
    id: 'it-q-3',
    title: 'Design a Distributed Rate Limiter (Token Bucket / Sliding Window)',
    domain: 'it',
    company_ids: ['comp-uber', 'comp-amazon', 'comp-google', 'comp-atlassian'],
    company_names: ['Uber', 'Amazon', 'Google', 'Atlassian'],
    category: 'System Design',
    subtopic: 'Distributed Systems',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Design an API rate limiter capable of enforcing a limit of 100 requests per minute per user across a cluster of 50 microservice instances. Discuss storage, concurrency, and algorithm choices.',
    answer_outline: 'Algorithm: Sliding Window Counter combining memory efficiency of fixed window with accuracy of sliding log. Storage: Redis distributed cache storing user token counters with TTL. Concurrency: Redis pipeline with Lua scripts to ensure atomic increment and expiration check without race conditions. Distributed sync: Consistent hashing to partition traffic by user_id across Redis shards. Fallback: If Redis is unavailable, rate limiter defaults to permissive pass-through to prevent breaking user login.',
    key_concepts: ['Token Bucket', 'Sliding Window Counter', 'Redis Lua Script', 'Atomic Increment', 'Consistent Hashing']
  },
  {
    id: 'it-q-4',
    title: 'LRU Cache Implementation with O(1) Get and Put',
    domain: 'it',
    company_ids: ['comp-amazon', 'comp-microsoft', 'comp-flipkart', 'comp-walmart'],
    company_names: ['Amazon', 'Microsoft', 'Flipkart', 'Walmart Global Tech'],
    category: 'DSA & Problem Solving',
    subtopic: 'Hashmap & Doubly Linked List',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache with get(key) and put(key, value) in O(1) average time complexity.',
    answer_outline: 'Use a Hashmap combined with a Doubly Linked List (DLL). Hashmap maps key -> Node pointer in DLL for O(1) lookup. DLL maintains access order: most recently used nodes are moved to head; least recently used nodes reside at tail. Dummy head and dummy tail nodes simplify edge cases (inserting/deleting first or last element without null checks).',
    code_snippet: 'class LRUCache {\n    struct Node { int k, v; Node *prev, *next; Node(int k, int v): k(k), v(v), prev(nullptr), next(nullptr){} };\n    int cap;\n    unordered_map<int, Node*> mp;\n    Node *head, *tail;\n    void remove(Node* n) { n->prev->next = n->next; n->next->prev = n->prev; }\n    void addHead(Node* n) { n->next = head->next; n->prev = head; head->next->prev = n; head->next = n; }\npublic:\n    LRUCache(int capacity) : cap(capacity) { head = new Node(0,0); tail = new Node(0,0); head->next = tail; tail->prev = head; }\n    int get(int key) {\n        if (!mp.count(key)) return -1;\n        remove(mp[key]); addHead(mp[key]);\n        return mp[key]->v;\n    }\n    void put(int key, int value) {\n        if (mp.count(key)) { remove(mp[key]); mp[key]->v = value; addHead(mp[key]); return; }\n        if (mp.size() == cap) { Node* lru = tail->prev; remove(lru); mp.erase(lru->k); delete lru; }\n        Node* n = new Node(key, value); mp[key] = n; addHead(n);\n    }\n};',
    key_concepts: ['Doubly Linked List', 'Hashmap', 'O(1) Eviction', 'Dummy Sentinel Nodes'],
    practice_url: 'https://leetcode.com/problems/lru-cache/'
  },
  {
    id: 'it-q-5',
    title: 'Explain ACID Properties & Database Indexing (B+ Tree vs Hash)',
    domain: 'it',
    company_ids: ['comp-oracle', 'comp-tcs', 'comp-infosys', 'comp-capgemini'],
    company_names: ['Oracle', 'TCS', 'Infosys', 'Capgemini'],
    category: 'DBMS & SQL',
    subtopic: 'Database Internals',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Define ACID properties with concrete e-commerce banking examples. Why do relational databases use B+ Trees instead of Binary Search Trees or Hash Tables for disk-based indexing?',
    answer_outline: 'ACID: Atomicity (All or nothing debit/credit transfer), Consistency (Database state valid across constraints), Isolation (Concurrent transactions do not see dirty intermediate writes), Durability (Committed transactions survive crashes via WAL). Indexing: B+ Tree has huge branching factor (fan-out of 100+), keeping tree height low (3-4 levels) to minimize disk I/O seeks. Leaf nodes are linked sequentially in a doubly linked list, enabling fast O(log N) range scans (WHERE age BETWEEN 20 AND 30). Hash indexing does not support range scans.',
    key_concepts: ['ACID', 'B+ Tree Fan-out', 'Range Queries', 'Disk I/O', 'Write-Ahead Logging']
  },
  {
    id: 'it-q-6',
    title: 'Course Schedule II (Topological Sort / Kahns Algorithm)',
    domain: 'it',
    company_ids: ['comp-google', 'comp-amazon', 'comp-microsoft', 'comp-uber'],
    company_names: ['Google', 'Amazon', 'Microsoft', 'Uber'],
    category: 'DSA & Problem Solving',
    subtopic: 'Graph Algorithms',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [a, b] indicates that you must take course b before taking course a. Return the ordering of courses you should take to finish all courses. If impossible, return an empty array.',
    answer_outline: 'Use Kahn\'s Algorithm (BFS with In-degree count): Calculate in-degree for every vertex. Push all vertices with in-degree 0 to queue. While queue is not empty, pop u, add to result order, and decrement in-degree of all neighbors v. If a neighbor in-degree reaches 0, push to queue. If result array size equals numCourses, return ordering; otherwise, a cycle exists (deadlock) so return empty array.',
    code_snippet: 'vector<int> findOrder(int n, vector<vector<int>>& prereqs) {\n    vector<vector<int>> adj(n);\n    vector<int> inDegree(n, 0), order;\n    for (auto& p : prereqs) { adj[p[1]].push_back(p[0]); inDegree[p[0]]++; }\n    queue<int> q;\n    for (int i = 0; i < n; i++) if (inDegree[i] == 0) q.push(i);\n    while (!q.empty()) {\n        int u = q.front(); q.pop(); order.push_back(u);\n        for (int v : adj[u]) if (--inDegree[v] == 0) q.push(v);\n    }\n    return order.size() == n ? order : vector<int>();\n}',
    key_concepts: ['Kahns Algorithm', 'Topological Sort', 'Cycle Detection in Directed Graph', 'In-degree BFS'],
    practice_url: 'https://leetcode.com/problems/course-schedule-ii/'
  },
  {
    id: 'it-q-7',
    title: 'Process vs Thread, Memory Layout, and Context Switching',
    domain: 'it',
    company_ids: ['comp-microsoft', 'comp-adobe', 'comp-cisco', 'comp-tcs'],
    company_names: ['Microsoft', 'Adobe', 'Cisco', 'TCS'],
    category: 'Operating Systems & Concurrency',
    subtopic: 'OS Fundamentals',
    difficulty: 'Easy',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'What are the architectural differences between a Process and a Thread? What resources are shared between threads of the same process, and why is thread context switching faster than process context switching?',
    answer_outline: 'A process is an executing program instance with isolated virtual address space (Code, Data, Heap, Stack, File Descriptors). Threads within a process share the same text, heap, and open files, but each thread possesses its own private Stack, Program Counter (PC), and CPU registers. Thread context switching is faster because virtual memory page tables (TLB - Translation Lookaside Buffer) do not need to be flushed, whereas process context switches trigger costly TLB cache invalidation and page table base register reload.',
    key_concepts: ['Process Address Space', 'Thread Stack & Registers', 'TLB Invalidation', 'Context Switch Overhead']
  },
  {
    id: 'it-q-8',
    title: 'TCP 3-Way Handshake & 4-Way Teardown vs UDP',
    domain: 'it',
    company_ids: ['comp-cisco', 'comp-oracle', 'comp-amazon', 'comp-infosys'],
    company_names: ['Cisco', 'Oracle', 'Amazon', 'Infosys'],
    category: 'Computer Networks',
    subtopic: 'Transport Layer Protocols',
    difficulty: 'Easy',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Explain the TCP 3-way handshake (SYN, SYN-ACK, ACK) and 4-way termination (FIN, ACK, FIN, ACK). Why is the TIME_WAIT state necessary on the client side?',
    answer_outline: 'Handshake: 1. Client sends SYN (seq=x). 2. Server replies with SYN-ACK (seq=y, ack=x+1). 3. Client sends ACK (ack=y+1). Connection established. Termination: 1. Client sends FIN. 2. Server sends ACK. 3. Server finishes and sends FIN. 4. Client replies with ACK and enters TIME_WAIT state (typically 2*MSL = 2 minutes). TIME_WAIT ensures delayed duplicate packets in the network do not corrupt subsequent new connections on the same port, and guarantees the server receives the final ACK (re-sending FIN if lost).',
    key_concepts: ['3-Way Handshake', 'TIME_WAIT State', '2*MSL', 'SYN Flood Attack', 'Reliable Delivery']
  },
  {
    id: 'it-q-9',
    title: 'Design a Scalable URL Shortener (TinyURL)',
    domain: 'it',
    company_ids: ['comp-uber', 'comp-amazon', 'comp-adobe', 'comp-flipkart'],
    company_names: ['Uber', 'Amazon', 'Adobe', 'Flipkart'],
    category: 'System Design',
    subtopic: 'High-Level Architecture',
    difficulty: 'Medium',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Design a TinyURL service that handles 100M new URLs per month with a 10:1 read-to-write ratio. Discuss encoding algorithm (Base62 vs MD5 hash), database schema, and high-speed redirection.',
    answer_outline: 'Architecture: 1. Base62 Encoding ([a-z, A-Z, 0-9] = 62 characters). 7 characters provide 62^7 = ~3.5 Trillion unique URLs. 2. Unique ID Generator: Distributed auto-increment ID generation (Snowflake or ZooKeeper range allocation) ensures collision-free IDs without hash collision retry loops. 3. Database: NoSQL key-value store (Cassandra or DynamoDB) or relational DB with (id, original_url, short_code, created_at). 4. Caching: Redis cluster caching top 20% hottest URLs (80-20 Pareto principle) for sub-5ms 301/302 redirects.',
    key_concepts: ['Base62 Encoding', 'Snowflake ID', 'Cache Aside', 'HTTP 301 vs 302', 'High Read-Throughput']
  },
  {
    id: 'it-q-10',
    title: 'Median of Two Sorted Arrays in O(log(min(m, n))) Time',
    domain: 'it',
    company_ids: ['comp-google', 'comp-microsoft', 'comp-amazon', 'comp-goldman'],
    company_names: ['Google', 'Microsoft', 'Amazon', 'Goldman Sachs'],
    category: 'DSA & Problem Solving',
    subtopic: 'Binary Search',
    difficulty: 'Hard',
    frequency: 'High',
    round_type: 'Technical',
    question_text: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).',
    answer_outline: 'Binary Search on the partition of the smaller array. Partition nums1 at index i and nums2 at index j such that left half contains (m + n + 1) / 2 elements. Check if maxLeft1 <= minRight2 and maxLeft2 <= minRight1. If true, correct partition found. If maxLeft1 > minRight2, move binary search left; otherwise move right. Time complexity O(log(min(m, n))), space O(1).',
    code_snippet: 'double findMedianSortedArrays(vector<int>& A, vector<int>& B) {\n    if (A.size() > B.size()) return findMedianSortedArrays(B, A);\n    int m = A.size(), n = B.size(), l = 0, r = m;\n    while (l <= r) {\n        int i = l + (r - l) / 2, j = (m + n + 1) / 2 - i;\n        int maxL1 = (i == 0) ? INT_MIN : A[i - 1], minR1 = (i == m) ? INT_MAX : A[i];\n        int maxL2 = (j == 0) ? INT_MIN : B[j - 1], minR2 = (j == n) ? INT_MAX : B[j];\n        if (maxL1 <= minR2 && maxL2 <= minR1) {\n            if ((m + n) % 2 == 1) return max(maxL1, maxL2);\n            return (max(maxL1, maxL2) + min(minR1, minR2)) / 2.0;\n        } else if (maxL1 > minR2) r = i - 1;\n        else l = i + 1;\n    }\n    return 0.0;\n}',
    key_concepts: ['Binary Search on Partition', 'Logarithmic Complexity', 'Array Balancing'],
    practice_url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/'
  }
];

export function getQuestionsByDomain(domain?: 'it' | 'ece' | 'all'): InterviewQuestion[] {
  if (!domain || domain === 'all') return INTERVIEW_QUESTIONS;
  return INTERVIEW_QUESTIONS.filter(q => q.domain === domain);
}

export function getQuestionsByCompany(companyIdOrName: string): InterviewQuestion[] {
  const query = companyIdOrName.toLowerCase();
  return INTERVIEW_QUESTIONS.filter(q => 
    q.company_ids.some(id => id.toLowerCase().includes(query)) ||
    q.company_names.some(name => name.toLowerCase().includes(query))
  );
}

export function getUniqueCategories(domain?: 'it' | 'ece' | 'all'): string[] {
  const list = getQuestionsByDomain(domain);
  return Array.from(new Set(list.map(q => q.category))).sort();
}
